name: Production

on:
  push:
    branches:
      - master
jobs:
  sync:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Sync with other languages
      uses: unraid/translation-sync-action
      with:
        languages: 'nl_NL,es_ES'